### PR TITLE
Xieyang ly patch project generate

### PR DESCRIPTION
**Pull request by XieyangLy**
add a way to generate only one specific project,but not all project

### CODE REVIEW

**Comment by brianesquilona** [comment]
morph test

**Comment by XieyangLy** [comment]
> 
> 
> /morph test

i can't open the details link,could you past the test result here ? or tell me what's wrong with the pr.

**Comment by brianesquilona** [comment]
@XieyangLy  can you sign [https://os.mbed.com/contributor_agreement/](https://os.mbed.com/contributor_agreement/)

**Comment by XieyangLy** [comment]
> 
> 
> @XieyangLy can you sign https://os.mbed.com/contributor_agreement/

may i try it

**Comment by XieyangLy** [comment]
> 
> 
> @XieyangLy can you sign https://os.mbed.com/contributor_agreement/
i just want to shared the way that only generator one project.so i pull a request。after i read the page of  https://os.mbed.com/contributor_agreement/,i also doon't konw what should i do next。in the workflow if the pr check pass，it will be wait merge。should i do one more thing?

**Pull request merged**
