### PR TITLE
Add support for module test boards

### PR DESCRIPTION
**Pull request by c1728p9**
Add target and board info for the following boards:
WISE-1510
WISE-1530
WISE-1570

### CODE REVIEW

**Comment by c1728p9** [comment]
Added the MTB MXCHIP EMW3166 board

**Comment by c1728p9** [comment]
Murata board added. Image built from https://github.com/mbedmicro/FlashAlgo/pull/39

**Comment by c1728p9** [comment]
Rebased to master

**Comment by pan-** [comment]
@c1728p9 Do you know when these targets support this will be officially released ? 
The `MTB_UBLOX_NINA_B1` target needs these changes to work and is already present on mbed-os master.

**Comment by c1728p9** [comment]
@pan- ideally a release would be created this week.

**Pull request merged**
