### PR TITLE
new hic: stm32f072cb experimental compilers

### PR DESCRIPTION
**Pull request by dotnfc**
@mbrossard:  PR #674  adapted for 'experimental_compilers' branch.

compile & link & run on eva board passed for armcc, argclang, arm_gcc and uvserison.

### CODE REVIEW

**Comment by mbrossard** [comment]
I made some minor changes in [mbrossard/DAPLink:feature/stm32f072cb_hic](https://github.com/mbrossard/DAPLink/tree/feature/stm32f072cb_hic). I am thinking [7f53b71] should be squashed with your commit to avoid unnecessary additions.

I am also working on STM32F072B-DISCO IO Config override (because it would require some soldering otherwise) to be able to test.

Looking at the STM32F072 specifications (DS9826 Rev 6) either there are some mistakes in the J-LINK OB pinout  or there are undocumented features: I don't see how you can enable HW flow control CTS/RTS on PA6/PA7.

Can you close #674?

**Comment by dotnfc** [comment]
#674 has been closed, and the HWFW has not been impl in my PR.

**Comment by mathias-arm** [comment]
I did re-base branch and squash the commit I mentioned earlier. The STM32F072B-DISCO is still a work-in-progress.

**Comment by mathias-arm** [comment]
@dotnfc: can you check that my branch (without last commit) works on your board. I am trying to locate better platform than  STM32F072B-DISCO to test.

**Comment by dotnfc** [comment]
i tried 'https://github.com/mbrossard/DAPLink/tree/feature/stm32f072cb_hic'(uv5) on my board, IT WORKS.
hic f072cb, target nucleo-f103rb

**Comment by zjli-2019** [comment]
I have just tried [mbrossard/DAPLink:feature/stm32f072cb_hic](https://github.com/mbrossard/DAPLink/tree/feature/stm32f072cb_hic) on **STM32F072C8** which has half size of flash, and got no luck.

I can find CMSIS DAP/COM in device manager, but neither `pyocd` nor `keil` uv5 can use it.

Looking into `DAP_Info`, when opening settings of CMSIS-DAP in uv5, only `DAP_ID_PRODUCT` is queried.

Any tips?

**Comment by zjli-2019** [comment]
After changing `CMSIS_DAP_PRODUCT_NAME` to `"CMSIS-DAP"`, it works in uv5.

**Comment by mbrossard** [comment]
Replaced by #991

**Pull request closed without merging**
