### PR TITLE
Add support for GigaDevice

### PR DESCRIPTION
**Pull request by MikeXiaoshi**

### CODE REVIEW

**Comment by MikeXiaoshi** [comment]
@brianesquilona please help us check it as soon as you can, thanks a lot

**Comment by brianesquilona** [comment]
mbed cli failed in this compile, At first glance, the core could be wrong in the hic's yaml file


0:13:32.657 Building project daplink (gd32f303xe_gd32f307vg_if, ARM)
00:13:32.657 Scan: daplink
00:13:33.358 Compile [  1.3%]: gd32f307vg.c
00:13:33.438 Compile [  2.6%]: HardFault_Handler.c
00:13:33.454 Compile [  3.9%]: RTX_Config.c
00:13:33.505 Compile [  5.3%]: circ_buf.c
00:13:33.538 Compile [  6.6%]: DAP_vendor.c
00:13:33.539 Compile [  7.9%]: SWO.c
00:13:33.548 Compile [  9.2%]: JTAG_DP.c
00:13:33.561 Compile [ 10.5%]: crc16.c
00:13:33.575 Compile [ 11.8%]: crc32.c
00:13:33.584 Compile [ 13.2%]: usbd_user_hid.c
00:13:33.594 Compile [ 14.5%]: flash_intf.c
00:13:33.617 Compile [ 15.8%]: cortex_m.c
00:13:33.617 Compile [ 17.1%]: flash_decoder.c
00:13:33.626 Compile [ 18.4%]: file_stream.c
00:13:33.640 Compile [ 19.7%]: DAP.c
00:13:33.652 Compile [ 21.1%]: flash_manager.c
00:13:33.661 Compile [ 22.4%]: intelhex.c
00:13:33.671 Compile [ 23.7%]: iap_flash_intf.c
00:13:33.671 Compile [ 25.0%]: error.c
00:13:33.714 Compile [ 26.3%]: SW_DP.c
00:13:33.734 Compile [ 27.6%]: virtual_fs.c
00:13:33.735 Compile [ 28.9%]: info.c
00:13:33.744 Compile [ 30.3%]: bootloader_update.c
00:13:33.754 Compile [ 31.6%]: flash_hal.c
00:13:33.755 Compile [ 32.9%]: daplink.c
00:13:33.765 Compile [ 34.2%]: SVC_Table.s
00:13:33.775 Compile [ 35.5%]: swd_host_ca.c
00:13:33.786 Compile [ 36.8%]: sdk_stub.c
00:13:33.813 Compile [ 38.2%]: vfs_manager.c
00:13:33.822 Compile [ 39.5%]: vfs_user.c
00:13:33.843 Compile [ 40.8%]: usbd_user_cdc_acm.c
00:13:33.852 Compile [ 42.1%]: validation.c
00:13:33.872 Compile [ 43.4%]: target_flash.c
00:13:33.892 Compile [ 44.7%]: main.c
00:13:33.892 Compile [ 46.1%]: settings.c
00:13:33.902 Compile [ 47.4%]: settings_rom.c
00:13:33.922 Compile [ 48.7%]: startup_gd32f30x_hd.s
00:13:33.932 Compile [ 50.0%]: util.c
00:13:33.942 Compile [ 51.3%]: read_uid.c
00:13:33.953 Compile [ 52.6%]: FlashPrg.c
00:13:33.966 Compile [ 53.9%]: swd_host.c
00:13:33.976 Compile [ 55.3%]: usb_config.c
00:13:34.001 Compile [ 56.6%]: gpio.c
00:13:34.029 Compile [ 57.9%]: uart.c
00:13:34.049 Compile [ 59.2%]: gd32f30x_fwdgt.c
00:13:34.079 Compile [ 60.5%]: gd32f30x_misc.c
00:13:34.089 Compile [ 61.8%]: gd32f30x_gpio.c
00:13:34.099 Compile [ 63.2%]: usbd_gd32f303.c
00:13:34.099 Compile [ 64.5%]: gd32f30x_pmu.c
00:13:34.129 Compile [ 65.8%]: gd32f30x_fmc.c
00:13:34.139 Compile [ 67.1%]: rt_Event.c
00:13:34.159 Compile [ 68.4%]: system_gd32f30x.c
00:13:34.159 Compile [ 69.7%]: rt_List.c
00:13:34.169 Compile [ 71.1%]: rt_Mailbox.c
00:13:34.169 Compile [ 72.4%]: rt_Mutex.c
00:13:34.179 Compile [ 73.7%]: rt_MemBox.c
00:13:34.189 Compile [ 75.0%]: rt_Robin.c
00:13:34.199 Compile [ 76.3%]: rt_Semaphore.c
00:13:34.199 Compile [ 77.6%]: rt_Time.c
00:13:34.209 Compile [ 78.9%]: rt_Timer.c
00:13:34.219 Compile [ 80.3%]: target.c
00:13:34.230 Compile [ 81.6%]: HAL_CM4.c
00:13:34.230 [Error] HAL_CM4.c@146,0: A1854E: Unknown opcode 'VSTMDBEQ', maybe wrong target CPU?
00:13:34.230 [Error] HAL_CM4.c@164,0: A1854E: Unknown opcode 'VLDMIANE', maybe wrong target CPU?
00:13:34.230 [Error] HAL_CM4.c@240,0: A1854E: Unknown opcode 'VSTMDBEQ', maybe wrong target CPU?
00:13:34.230 [Error] HAL_CM4.c@257,0: A1854E: Unknown opcode 'VLDMIANE', maybe wrong target CPU?
00:13:34.304 [ERROR] ".\\source\\rtos\\cm4\\HAL_CM4.c", line 146: Error: A1854E: Unknown opcode 'VSTMDBEQ', maybe wrong target CPU?
00:13:34.304   146 00000096  VSTMDBEQ R12!,{S16-S31} 
00:13:34.304 ".\\source\\rtos\\cm4\\HAL_CM4.c", line 164: Error: A1854E: Unknown opcode 'VLDMIANE', maybe wrong target CPU?
00:13:34.304   164 000000c0  VLDMIANE R12!,{S16-S31} 
00:13:34.304 ".\\source\\rtos\\cm4\\HAL_CM4.c", line 240: Error: A1854E: Unknown opcode 'VSTMDBEQ', maybe wrong target CPU?
00:13:34.304   240 0000012c  VSTMDBEQ R12!,{S16-S31} 
00:13:34.304 ".\\source\\rtos\\cm4\\HAL_CM4.c", line 257: Error: A1854E: Unknown opcode 'VLDMIANE', maybe wrong target CPU?
00:13:34.304   257 00000156  VLDMIANE R12!,{S16-S31} 
00:13:34.304 4 Errors, 0 Warnings

**Comment by MikeXiaoshi** [comment]
@brianesquilona I know these errors, they are caused by the project_generator_definitions of GigaDevice. I have changed the file, please wait for merging

**Comment by MikeXiaoshi** [comment]
Hi @brianesquilona, the merging of the project_generator_definitions for GigaDevice has been finished, please build again, thanks a lot.

**Comment by brianesquilona** [comment]
Hi @MikeXiaoshi , thanks for the changes, it would be great if you can also send a patch to mbed-os tools directory, automated build for testing for Daplink is now based on mbedcli. You can find the targets in mbed-os/targets directory.

**Comment by flit** [comment]
Needs to be rebased. Also need signed CLA.

**Comment by 0xc0170** [comment]
> Needs to be rebased

Please rebase and provide test results

> Hi @MikeXiaoshi , thanks for the changes, it would be great if you can also send a patch to mbed-os tools directory, automated build for testing for Daplink is now based on mbedcli. You can find the targets in mbed-os/targets directory.

Still needed?

**Comment by 0xc0170** [comment]
I'll close this as it has not been touched for months. Please reopen with an update.

**Pull request closed without merging**
