### PR TITLE
Add Nuvoton NuMaker-PFM-M487 board

### PR DESCRIPTION
**Pull request by ychsu-tf**

### CODE REVIEW

**Review by 0xc0170 — APPROVED** [review]

**Comment by mbrossard** [comment]
I am a little bit surprised. When I looked up the board, the [Mbed entry for NuMaker-PFM-M487](https://os.mbed.com/platforms/numaker-PFM-M487/) says that it "is fitted with an NUC12SRE3DE MCU running the DAPLink interface firmware".
Nu-Link-Me is based on NUC12SRE3DE when Nu-Link2-Me is based on M485SIDAE.

There is a [NuMaker-PFM-M487KM](https://www.nuvoton.com/board/numaker-pfm-m487km) board with a Nu-Link2-Me. If this is actually the board for which support is being added. I would suggest to add the `km` suffix to all mentions of the board name (including filename) to avoid confusion.

**Comment by flit** [comment]
@ychsu-tf Apologies it's taken a long time to follow up on this! (We've had a lot of CI issues that have been really difficult to resolve because we haven't been able to get to the office due to the pandemic.)

If you still want to merge, I'd like to move forward, otherwise we can close this PR. I think it would be best to rebase 

Can you please respond regarding the question/suggestion from @mbrossard about the "KM" board name suffix? Thanks!

**Comment by ychsu-tf** [comment]
@flit My apologies for the late response. I have rebased this branch and added the suffix according to the suggestion from @mbrossard. Thank you for taking the time to review this pull request.

**Review by flit — APPROVED** [review]

**Pull request merged**
