### PR TITLE
LPC54608/LPC54114: Set the REMMAP register to user flash mode

### PR DESCRIPTION
**Pull request by mmahadevan108**
Fix for Issue#346

Signed-off-by: Mahesh Mahadevan <Mahesh.Mahadevan@nxp.com>

### CODE REVIEW

**Comment by mmahadevan108** [comment]
This PR should fix https://github.com/ARMmbed/DAPLink/issues/346

**Comment by c1728p9** [comment]
Thanks for the PR @mmahadevan108

**Pull request merged**
