### PR TITLE
Add KW41Z support

### PR DESCRIPTION
**Pull request by mmahadevan108**

### CODE REVIEW

**Comment by mmahadevan108** [comment]
cc @flit @maclobdell @jasonNXP @c1728p9

**Comment by mmahadevan108** [comment]
Updated PR to include custom volume name etc.

**Comment by mmahadevan108** [comment]
Can this be merged in

**Comment by mmahadevan108** [comment]
@c1728p9 Can you help provide more details on the test failures.

**Comment by c1728p9** [comment]
Hi @mmahadevan108 the failure reported is an internal failure. I'll re-trigger and let you know if there are any real failures.

**Pull request merged**
