### PR TITLE
Merge MAX32620/30/60 target reset feature

### PR DESCRIPTION
**Pull request by ozersa**
Signed-off-by: Sadik.Ozer <Sadik.Ozer@maximintegrated.com>

### CODE REVIEW

**Comment by ozersa** [comment]
Thanks for feedback, 
I am trying to remove code duplication,
The macro define in .yaml file

https://github.com/ARMmbed/DAPLink/pull/865/commits/533760882c2b45d9fc4da7348cc5b2208780a90c#diff-f3a06f2092799268f0e3d364246ca4706cf8a5f60d641a3cd7cef5bcebb78ffcR9

Is this method forbidden? I would appreciate if I learn reason.
Thank you.

**Comment by mathias-arm** [comment]
Having macro defines in the board .yaml file is allowed, but it should not affect families. They should be added to `records/family/all_family.yaml` which ends up being included in many projects.

**Comment by ozersa** [comment]
Can it be merged as it is?

**Comment by mathias-arm** [comment]
The goal of families is to build target-independent interface firmwares. One of the goal is to be able to support assembling a HIC interface firmware base with a target-specific part in post-processing. It would also a necessary to an interface firmware that would detect the target and automatically configure itself accordingly.

**Comment by ozersa** [comment]
Thanks for the information, 
Related modification has been applied.

**Pull request merged**
