### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by tarokajya**
I found a typo in source/hic_hal/read_uid.h.
This patch will fix typo.

--- read_uid.h.orig     Mon Feb 12 14:01:00 2018
+++ read_uid.h  Mon May 21 13:49:10 2018
@@ -25,7 +25,7 @@
 #include "stdint.h"

 #ifdef __cplusplus
-}
+extern "C" {
 #endif

 void read_unique_id(uint32_t *id);

### CODE REVIEW

**Comment by tarokajya** [comment]
Any progress?
I also found another typo. Please refer my commits.
Thank you.

**Comment by flit** [comment]
@tarokajya Thanks for your fixes!

**Pull request merged**
