### PR TITLE
VFS/VBR/FAT Boot Sector Signature + Bootstrap Code / Android USB OTG FIX

### PR DESCRIPTION
**Pull request by cederom**
**This PR fixes Android USB OTG mount problem**
When Disk Boot Signature is not `0xAA55` (note hexdump order `55 AA`) then Android cannot mount DAPLink and considers it a broken drive. This prevented mount on Android USB OTG due to internal `fsck_msdos` failure on check before mount. This signature shall remain `0xAA55` to indicate Sector 0 end as defined by standard!

**This PR adds new PC Bootstrap Code**
As Boot Signature was marked `0xAA55` some systems may consider it bootable. Because "accidental" boot from USB DAPLink could cause trouble and confuse some users, I have created a simple PC Bootloader that prints out warning message on the computer screen when booted from USB DAPLink:
```
PLEASE REMOVE THE ARM MBED DAPLINK USB DEVICE AND REBOOT THE SYSTEM..
```
The bootloader source code and compiler script plus payload generator is attached in VFS sources. Someone with experience in x86 bootloader design should verify the code please. Modifications should be trivial to follow.

**Big Thank You to Microbit Community for pointing out the https://github.com/ARMmbed/DAPLink/issues/269 problem and Google Support + Developers for Testing and pointing out the hints on Android internals! :-)**

https://issuetracker.google.com/issues/73130696

### CODE REVIEW

**Comment by jaustin** [comment]
This is fantastic, thanks @cederom !
@c1728p9 we'd be keen to know whether this is likely to make it into 0247? Do we need additional testing due to these changes?

**Comment by brianesquilona** [comment]
Unfortunately having this signature makes some PC think that it can boot from the DAPLink drive, although the prints are useful, in CI, we need to configure the PC not to boot on some drives which is a bit of trouble on restart.

**Comment by cederom** [comment]
Hello @brianesquilona, I understand the problem, here are some remarks:
* `0xAA55` signature is required by some `msdos_fsck` to verify clean filesystem and attach the drive (i.e. Android or FreeBSD). Because there was no signature Android considered disk to be broken.
* `0xAA55` may be used to mark disk bootable.. but its also used to detect valid filesystem.
* We are using VBR not the MBR.

Fixes may include:
* Configure CI machines BIOS/SETUP correctly:
   * Disable USB boot at all. You still may use USB boot with F12 or F8 or ESC (depends on machine) Boot Menu triggered by hand when necessary.
   * Use internal SATA or selected external Hard-Drive only as the only boot medium. Disable all other boot devices. That would prevent accidental boot from unwanted devices.
   * Use UEFI boot. That will ignore BIOS/MBR boot devices. You would have to use UEFI aware OS on the CI machines.
* Search for a bit in VBR structures that marks disk bootable (something else than `0xAA55` signature.. I think there was one specific bit that could be used here but I don't remember exactly now sorry).
* Maybe the bootloader code may return error value or trigger boot from a next device.
* Treat VBR as MBR, describe disk as first and only partition, but NOT active. That would give us both valid disk signature and non-bootable partition.
* Implement MBR in addition to VBR to have most desirable and versatile solution.
* Forget about MBR and switch to GPT. That would break backwards-compatibility with older systems.

**Comment by flit** [comment]
Fwiw, I completely agree that the 0xaa55 signature is required. It's not a valid filesystem with this signature missing. We need to find some other mechanism to prevent PCs from trying to boot from the DAPLink volume.

**Comment by jaustin** [comment]
Hey @brianesquilona did you find a workaround to the booting issues described above, hence the merge? Given the number of schools that want to leave micro:bits plugged in and reboot machines, etc, I'd like to make sure we know about the implications of this one in advance :)

**Comment by cederom** [comment]
Hey Johny, the simplest solution would be to setup BIOS settings as presented above. DAPLink will print a message on screen so you clearly know when machine boots off it.. maybe there is another way, when found it will go to upstream..

**Comment by jaustin** [comment]
@cederom thanks for the quick response, unfortunately with more than 2M micro:bits in different kinds of school systems now it's hard for us to make recommendations about bios setup - even just having to install a driver, or application, is a significant barrier for using tech in schools, and one of the reasons DAPLink helps so much!

Likewise, even with the helpful message printed, I think people will potentially be very confused - to most teachers or students users, the phrase "ARM MBED DAPLINK" doesn't mean (yet! hopefully the point is they'll learn much more as they get into coding) so may not even help them identify which device to remove.

...so if this change is going upstream, and machines will still try to boot from any connected DAPLink device, it would be really good if we could make the change optional at build time?

**Comment by brianesquilona** [comment]
@jaustin the signature is a standard to comply with FAT standard. I don't know about other PC machines but on some Dell systems, without this signature, the drive was mistaken to be a diskette drive and on legacy boot, some machines will still boot from it even without the signature and will just print a general boot error on the screen. At least this PR prints an error if the system mistakenly booted on the DAPLink drive.

**Comment by cederom** [comment]
This also makes DAPLink work on Android ;-)

**Comment by flit** [comment]
We could potentially make the message configurable per board.

Without this change, the FAT filesystem from DAPLink is invalid and corrupt. I'm really surprised that any OSes will mount the volume. Android is doing the correct thing by reporting a corrupted filesystem and refusing to mount it.

We will look at adding an MBR and see if there's anything we can do there.

**Pull request merged**
