### PR TITLE
add new hci stm32f072xx

### PR DESCRIPTION
**Pull request by zjli-2019**
This based on PR https://github.com/ARMmbed/DAPLink/pull/805 and [mbrossard/DAPLink:feature/stm32f072cb_hic](https://github.com/mbrossard/DAPLink/tree/feature/stm32f072cb_hic), with following updates:

1. updated with `main` branch;
2. Generalized to support all stm32f072xx such as stm32f072cb and stm32f072c8, if flash size is large enough.

PS: Regarding the project generation of stm32f072c8, there is a PR https://github.com/project-generator/project_generator_definitions/pull/151.

### CODE REVIEW

**Comment by elfmimi** [comment]
stm32f0728_if , this naming is inconsistent with others like stm32f103xb_if. I suppose it should be stm32f072x8_if.
Same for hic_stm32f072cb , module_hic_stm32f072cb , stm32f072cb.yaml , hic_stm32f072c8 and module_hic_stm32f072c8 .

File records/board/stm32f072b_disco.yaml seems to be missing.
Besides, in stm32f072b_disco_if , first part designates interface chip. hence I believe it will be stm32f103xb_stm32f072bdisco_if .

**Comment by elfmimi** [comment]
Shouldn't https://github.com/mbrossard/DAPLink/blob/feature/stm32f072cb_hic/source/board/IO_Config_Override.h be 
located at source/board/**override_stm32f072b_disco**/IO_Config_Override.h ?

**Comment by mbrossard** [comment]
> Shouldn't https://github.com/mbrossard/DAPLink/blob/feature/stm32f072cb_hic/source/board/IO_Config_Override.h be located at source/board/**override_stm32f072b_disco**/IO_Config_Override.h ?

Nice catch.

**Comment by mbrossard** [comment]
> This based on PR #805 and [mbrossard/DAPLink:feature/stm32f072cb_hic](https://github.com/mbrossard/DAPLink/tree/feature/stm32f072cb_hic), with following updates:
> 1. updated with `main` branch;

I just rebased [mbrossard/DAPLink:feature/stm32f072cb_hic](https://github.com/mbrossard/DAPLink/tree/feature/stm32f072cb_hic) onto `main`. Squashing the commits make it harder to understand your changes.

> 2. Generalized to support all stm32f072xx such as stm32f072cb and stm32f072c8, if flash size is large enough.

It seems your changes reduce the flash size to 64KB.

I have been looking at adding a `STM32F103C8` target, and similarly to `STM32F072CB` vs `STM32F072C8` it should not be a very invasive change.

**Comment by mbrossard** [comment]
Replaced by #991

**Pull request closed without merging**
