### PR TITLE
Adding board support for. CC3220sf

### PR DESCRIPTION
**Pull request by dragoniteArm**

### CODE REVIEW

**Comment by flit** [comment]
You are using a DIPDAP to connect to the CC3220SF, right? The name of the board should probably be `dipdap_cc3220sf`, to indicate that it's not an on-board debug probe.

**Comment by linlingao** [comment]
@brianesquilona I would like to wrap up this so that we can deliver this to our customer. Please let me know what you'd like me to do to help merge this PR.

**Comment by linlingao** [comment]
Abandon this PR. Replace it with https://github.com/ARMmbed/DAPLink/pull/520.

**Pull request closed without merging**
