### PR TITLE
Add Support for Toshiba AdBun-M46B board

### PR DESCRIPTION
**Pull request by ganesh-ramachandran**
Added Interface firmware for TMPM46B and Bootloader firmware for TMPM366

### CODE REVIEW

**Comment by 0xc0170** [comment]
Hi @ganesh-ramachandran . Can you rebase and retest this?

**Comment by ganesh-ramachandran** [comment]
> Hi @ganesh-ramachandran . Can you rebase and retest this?

Hi @0xc0170, Rebased and tested with the `python test\run_test.py --force --notestendpt --testdl --loadbl` command, but few fails were observed. The test result log files are attached. 

[tmpm366_tmpm46b_stk_if AdBun-M46B.txt](https://github.com/ARMmbed/DAPLink/files/3275972/tmpm366_tmpm46b_stk_if.AdBun-M46B.txt)

The test log is saying that the CRC in the bootloader image is not equal to the CRC listed in the details.txt and we also analyzed and found that in bootloader case only, CRC is different in details.txt and post-build script CRC.

```
Post build script CRCs:
Start 0x0, Length 0xe000, CRC32 0xb307df4a : Bootloader
Start 0x10000, Length 0x17000, CRC32 0x3921d32f : Interface

Details.txt CRCs:
Bootloader CRC: 0xdb5b65cb
Interface CRC: 0x3921d32f
```
Please suggest, how to fix this issue?

**Comment by ganesh-ramachandran** [comment]
Hi @0xc0170, @c1728p9, @cederom  this issue is similar to #314. Could you please confirm how #314 is resolved. We have disabled interrupts when performing flash ops. But still the issue occurs.
Can you please confirm.

**Comment by ganesh-ramachandran** [comment]
Hi @0xc0170, @c1728p9, @cederom, @flit, @brianesquilona We fixed the CRC issue and able to run the test, but one test case is still failing after executing below command:-
`python test\run_test.py --force --notestendpt --testdl --loadbl`

The test result log files are attached.

[summary.txt](https://github.com/ARMmbed/DAPLink/files/3471559/summary.txt)
[tmpm366_tmpm46b_stk_if AdBun-M46B.txt](https://github.com/ARMmbed/DAPLink/files/3471566/tmpm366_tmpm46b_stk_if.AdBun-M46B.txt)
[log_with_all_verbose.txt](https://github.com/ARMmbed/DAPLink/files/3471664/log.txt)

```
Test: tmpm366_tmpm46b_stk_if AdBun-M46B: Failure
  Test: daplink_test: Failure
    Test: bin bootloader filetype test: Failure
      Failure: Bootloader missing but file NEED_BL.TXT not present
      Failure: Board switched to bootloader mode
      Failure: Device in wrong mode
      Failure: Bootloader missing but file NEED_BL.TXT not present
      Failure: Bootloader missing but file NEED_BL.TXT not present
    Test: hex bootloader filetype test: Failure
      Failure: Bootloader missing but file NEED_BL.TXT not present
      Failure: Board switched to bootloader mode
      Failure: Device in wrong mode
      Failure: Bootloader missing but file NEED_BL.TXT not present
      Failure: Bootloader missing but file NEED_BL.TXT not present
```
[Test Case: test_file_type(Bootloader)](https://github.com/ARMmbed/DAPLink/blob/master/test/test_daplink.py#L196-L197)

As per our understanding test case is not able to create 'NEED_BL.TXT' file from [vfs_user.c](https://github.com/ARMmbed/DAPLink/blob/master/source/daplink/drag-n-drop/vfs_user.c#L113-L124) file.

And we are not getting in which condition ['if' is True](https://github.com/ARMmbed/DAPLink/blob/master/source/daplink/drag-n-drop/vfs_user.c#L116) because [daplink_is_interface()](https://github.com/ARMmbed/DAPLink/blob/master/source/daplink/bootloader/daplink.c#L38) is always returning false?

**Please suggest, how to fix this issue?**

**Comment by 0xc0170** [comment]
I don't have yet sufficient knowledge for this one to answer but will poke @brianesquilona

**Comment by brianesquilona** [comment]
Just a comment on this test, on interface mode, when flashing an invalid/partial bootloader image, it is expecting a failure and a file NEED_BL.TXT, the state of DAPLINK will be in interface mode for you to update the bootloader again.

**Comment by 0xc0170** [comment]
> Just a comment on this test, on interface mode, when flashing an invalid/partial bootloader image, it is expecting a failure and a file NEED_BL.TXT, the state of DAPLINK will be in interface mode for you to update the bootloader again.

@ganesh-ramachandran Does  this help?

**Comment by ganesh-ramachandran** [comment]
> > Just a comment on this test, on interface mode, when flashing an invalid/partial bootloader image, it is expecting a failure and a file NEED_BL.TXT, the state of DAPLINK will be in interface mode for you to update the bootloader again.
> 
> @ganesh-ramachandran Does this help?

Sorry, we thought it is just an info of the problem we are facing. We could not decode the above given comment for a solution. Is it possible to specify what exactly to be done.

**Comment by ganesh-ramachandran** [comment]
Will revise and create new PR.

**Pull request closed without merging**
