### PR TITLE
Add MAX32660EVSYS board

### PR DESCRIPTION
**Pull request by ozersa**
Signed-off-by: Sadik.Ozer <Sadik.Ozer@maximintegrated.com>

### CODE REVIEW

**Comment by mathias-arm** [comment]
It seems this PR duplicates functionality added #799. Could you work together to factorize this into one `kMaxim_MAX326xx_FamilyID` family with associated reset?

**Comment by ozersa** [comment]
Thanks for review and idea,
We would like to send a separate PR for that purpose.

**Comment by mathias-arm** [comment]
I created a rebased branch of both PR in [mathias-arm:fix/maxim-reset-main](https://github.com/mathias-arm/DAPLink/tree/fix/maxim-reset-main). I merged the max32620 and max32630 family, but noticed there is a small difference for max32660 (the flash controller bit is absent and its address is different anyways).

I am wondering if max32625 and max32665 targets should be modified as well.

Let me know what you think.

**Comment by ozersa** [comment]
Thanks, it needs for MAX32665 and MAX32625, 
These devices (MAX32620/25/60/65) has different die type so probably there will be same differentiation. 
The purpose of this feature it to able to wakeup target even in low power case.
So that it needs to be tested on hardware, especially when target in deepsleep mode.

**Comment by ozersa** [comment]
Again I prefer to centralize them on separate PR in future.
Thanks

**Comment by mathias-arm** [comment]
Ok I will merge this PR, and will expect other PR for other Maxim targets. Should #799 be closed?

**Comment by ozersa** [comment]
Yes please merge  #799 too.
Thank you.

**Comment by mathias-arm** [comment]
I looked and #799 needs to be rebased to be merged.

**Pull request merged**
