### PR TITLE
Unrevert K64F sector erase change

### PR DESCRIPTION
**Pull request by c1728p9**
Cherry pick #374 to master to re-enable sector erase on the K64F. This was initially reverted in #386.

### CODE REVIEW

**Comment by c1728p9** [comment]
CC @mmahadevan108

**Comment by maclobdell** [comment]
@mmahadevan108   Please review and let us know if you approve.  This is an urgent one that we believe will benefit security greatly by allowing the ability to reserve an area of flash.

**Comment by mmahadevan108** [comment]
Thank you @maclobdell @c1728p9 . Looks good to me.

**Pull request merged**
