### PR TITLE
More misc cleanup

### PR DESCRIPTION
**Pull request by flit**
- Cleanup of `main.h` headers.
- Merged `macro.h` into `util.h`
- Moved `ARRAY_SIZE()` macro to `util.h`, replacing `ELEMENTS_IN_ARRAY()`.
- Using a single definition of `MAX()` from `util.h`.
- Changed the `disc_size` constant in `vfs_user.c` to a macro.
- Replaced the weak, null family descriptor structs with weak references to those structs and a different terminator value for `g_families` (so entries in that array can be null without terminating the list).
- Changed most includes of C Standard Library headers to be system includes (angle brackets instead of quotes). Didn't touch vendor-supplied SDK sources for the most part.
- Trailing whitespace cleanup.

### CODE REVIEW

**Comment by 0xc0170** [comment]
Build failures in the CI logs, please review

**Comment by 0xc0170** [comment]
Most of the commits look fine, need to review them in more detail. One is adding new functionality: 2b61b1f9cc8b6eefffdacb3a8dfb023d46947017 , shouldn't this be in separate PR?

**Comment by flit** [comment]
Good point about the new hooks in 2b61b1f, I'll pull that into a separate PR.

**Comment by flit** [comment]
Split out several changes to new branches. They'll be merged after this one.

**Comment by 40Grit** [comment]
Nothing more refreshing then a big batch of refactor.

**Comment by flit** [comment]
Mac and Win failed with:

```
[1578670942.622000] SubTest: Build test configuration
[1578670942.622000] No board to test firmware sam3u2c_mkit_dk_dongle_nrf5x_if
[1578670942.622000] No board to test firmware sam3u2c_mkit_dk_dongle_nrf5x_if
[1578670942.622000] No board to test firmware sam3u2c_mkit_dk_dongle_nrf5x_if
[1578670942.622000] No target to test firmware sam3u2c_mkit_dk_dongle_nrf5x_if
[1578670942.622000] No board to test firmware sam3u2c_mkit_dk_dongle_nrf5x_if
[1578670942.622000] No board to test firmware kl26z_microbit_if
[1578670942.622000] Test configurations to be run:
[1578670942.622000]     0: APP=k20dx_frdmk82f_if BL=k20dx_bl Board=FRDM-K82F Target=FRDM-K82F
[1578670942.622000]     1: APP=k20dx_frdmkl82z_if BL=k20dx_bl Board=FRDM-KL82Z Target=FRDM-KL82Z
[1578670942.622000]     2: APP=k20dx_frdmk22f_if BL=k20dx_bl Board=FRDM-K22F Target=FRDM-K22F
[1578670942.622000]     3: APP=k20dx_frdmk64f_if BL=k20dx_bl Board=FRDM-K64F Target=FRDM-K64F
[1578670942.622000]     4: APP=kl26z_microbit_if BL=kl26z_bl Board=Microbit Target=Microbit
[1578670942.622000] 
[1578670942.622000] Fimrware that will not be tested:
[1578670942.622000]     sam3u2c_mkit_dk_dongle_nrf5x_if
[1578670942.622000] 
[1578670942.622000] Exiting because not all firmware could be tested
```

Linux failed with a USB timeout while testing CDC.

**Comment by flit** [comment]
The Linux tests are consistently failing (ignoring the apparent hw problems with Mac and Win), so there must be some problem introduced by this PR. I'm going to continue to break changes out from this one so the issue can hopefully be isolated.

**Comment by flit** [comment]
Rebased and dropped the changes that are now in #692 (and which seem to be causing trouble).

**Pull request merged**
