### PR TITLE
Add support for LPC55S69Xpresso board

### PR DESCRIPTION
**Pull request by mmahadevan108**
Signed-off-by: Mahesh Mahadevan <mahesh.mahadevan@nxp.com>

### CODE REVIEW

**Comment by mmahadevan108** [comment]
cc @flit @brianesquilona

**Comment by mmahadevan108** [comment]
cc @maclobdell

**Comment by flit** [comment]
@mmahadevan108 Were you going to change the memory map to include the secure regions? Or did you want to do that in a separate pull request? Fyi, we are planning to support multiple memory regions in the near future (#549).

**Comment by mmahadevan108** [comment]
Thank you Chris. I have added one more commit to this PR with the update to the binary validate check.

**Comment by flit** [comment]
@mmahadevan108 Fyi, #553 has been merged now. Please update this PR to make use of the multiple regions. If you run into any trouble with multiple regions, just let us know! Thanks.

**Comment by mmahadevan108** [comment]
I have updated the PR.

**Comment by brianesquilona** [comment]
@mmahadevan108 @flit, I have verified that the last morph test succeeded although the status was not reported here. Should we merge this PR now? 

The ci might be down until end of  holidays. I am planning to use this downtime to add the no msd feature option and so there will be changes on the way boards and targets are added.

**Comment by mmahadevan108** [comment]
Thank you, that would be great

**Comment by mmahadevan108** [comment]
Can this be merged?

**Comment by mmahadevan108** [comment]
Can this be merged?

**Comment by brianesquilona** [comment]
@mmahadevan108  I will need to check what's wrong with the CI firsts after we did the migration to the new lab, before I can merge the PRs

**Pull request merged**
