### PR TITLE
Add a DAPLink troubleshooting md to support micro:bit users

### PR DESCRIPTION
**Pull request by willlordarm**
Previously discussed with @0xc0170. 

All boards that have DAPLink support include a link to mbed.com:
 
`# DAPLink Firmware - see https://mbed.com/daplink`
 
This redirects here: https://os.mbed.com/daplink-on-kl26z/ which is focused on fixing a micro:bit issue.

Turns out that micro:bits also include the same link to https://mbed.com/daplink when they end up in maintenance mode. For this reason all visits to mbed.com/daplink are sent sent to a page that is primarily focused on micro:bit and has little relevance to most DAPLink users.

The addition of the troubleshooting guide means we can include the micro:bit info in addition to generic DAPLink documentation. We can then redirect https://mbed.com/daplink to https://github.com/ARMmbed/DAPLink/tree/master/docs so that both micro:bit and non-micro:bit users get the information they need.

### CODE REVIEW

**Comment by flit** [comment]
Would you mind squashing to a single commit? Thanks!

**Review by 0xc0170 — APPROVED** [review]

**Comment by 0xc0170** [comment]
I can merge via squash, lets run the test

**Comment by willlordarm** [comment]
@flit @0xc0170 thanks for the approval. Do you need me to do anything to fix the failing `ci-morph-test`?

**Comment by 0xc0170** [comment]
All good, tests are not related to this PR.

**Pull request merged**
