### PR TITLE
Add Seeed Wio EMW3166 target

### PR DESCRIPTION
**Pull request by toyowata**
Add Seeed Wio EMW3166 target (board_id = 9017)

cc @ARMmbed/team-seeed

### CODE REVIEW

**Comment by 0xc0170** [comment]
Any test logs?

**Comment by toyowata** [comment]
@0xc0170 Test result is below:

```
PS D:\work\DAPLink> python .\test\run_test.py --notestendpt --noloadif --firmware lpc11u35_wio_emw3166_if --targetdir D:\test\wio_emw3166
[1567130087.247000] SubTest: DAPLink
[1567130087.323000] SubTest: Build test configuration
[1567130087.324000] Test configurations to be run:
[1567130087.324000]     0: APP=lpc11u35_wio_emw3166_if BL=<None> Board=WIO_EMW3166 Target=<None>
[1567130087.325000]
[1567130087.325000] All firmware can be tested
[1567130087.326000]
[1567130087.326000] SubTest: lpc11u35_wio_emw3166_if WIO_EMW3166
[1567130087.326000] Board: Name=WIO_EMW3166 Unique ID=9017000001df236900000000000000000000000097969902
[1567130087.327000] Application: Name=lpc11u35_wio_emw3166_if
[1567130087.327000] Bootloader: None
[1567130087.328000] Target: None

Test: lpc11u35_wio_emw3166_if WIO_EMW3166: Pass

All boards passed
```

**Comment by 0xc0170** [comment]
Looks like morph not working for me

@brianesquilona @flit Can you try?

**Comment by 0xc0170** [comment]
I am checking test failing, I dont find them related to this PR, but need to check

**Comment by 0xc0170** [comment]
Not related to the PR, I'll try to find a way to resolve or will merge this with "known issue in macos tests not related here"

**Comment by 0xc0170** [comment]
Test failure is related to one machine not having devices connected, I'll try to get them back. Not related to this addition

**Pull request merged**
