### PR TITLE
Rework UART  implementation for MAX32625 HIC

### PR DESCRIPTION
**Pull request by khariya**
Added support for wide range of baud rates beyond 115200 for MAX32625 HIC along with other minor changes.

Tested on Windows 10 with MAX32630FTHR and MAX32620FTHR targets.

### CODE REVIEW

**Comment by khariya** [comment]
Any update on this PR?

**Review by 0xc0170 — APPROVED** [review]

**Comment by khariya** [comment]
I'm unable to check the details for the failing test, the server is not responding. Is there an alternate way to check the error?

**Comment by cederom** [comment]
Hey @khariya take a look at https://github.com/ARMmbed/DAPLink/pull/750 the GCC builds are now available to test!! Go and test builds then operations on your local setup :-)

**Comment by flit** [comment]
@khariya Don't worry about the CI failures. The CI system is having lots of issues with the boards lately, and it's all about to be relocated from Austin to Cambridge (UK).

**Pull request merged**
