### PR TITLE
Rename reset_stop_on_reset() to reset_and_halt()

### PR DESCRIPTION
**Pull request by khariya**
Match the function name with pyocd tools.

### CODE REVIEW

**Comment by flit** [comment]
We can't merge this yet because DAPLink is pinned to pyOCD version 0.15.0, which doesn't have the `reset_and_halt()` name change. After v0.16.0 is released with the name change, we'll be able to merge this PR. But you'll need to update the pyOCD version in `requirements.txt`.

**Comment by flit** [comment]
@khariya Can you update `requirements.txt` to set the pyOCD version to 0.16.0? Then we can merge in this PR. Thanks!

**Comment by khariya** [comment]
I'm sorry for the delay.

**Pull request merged**
