### PR TITLE
Added script for release build in Linux (mainly)

### PR DESCRIPTION
**Pull request by brianesquilona**

### CODE REVIEW

**Comment by brianesquilona** [comment]
daplink_build_mbedcli_pr 42
daplink_test_mbedcli_pr 30

**Comment by brianesquilona** [comment]
@cederom Thanks for your comment, I have only tested this in Linux, and I'm about to make a release with this merge. You can try it in Unix and make some modifications, and I will accept the changes :).

**Comment by cederom** [comment]
Allright, thanks, just wanted to know if you are somehow tied to Linux/Bash :-) I can provide testing and patches for FreeBSD and macOS BSD, just let me know if you need any assistance in this area :-)

**Pull request merged**
