### PR TITLE
add a new hic STM32F072CB

### PR DESCRIPTION
**Pull request by dotnfc**
new hic using STM32F072CB chip, it is an ideal daplink interface for small project.

this request is a replacement of [#495](https://github.com/ARMmbed/DAPLink/pull/495)

### CODE REVIEW

**Comment by 0xc0170** [comment]
I'll try to review this addition this week.

**Comment by flit** [comment]
I'd prefer to wait on this one until gcc support is integrated, if that's ok. Any new HICs will just add to the porting effort…

**Comment by mathias-arm** [comment]
@dotnfc: could you rebase your changes on the `experimental_compilers` branch and do a pull request to that branch?

**Comment by mbrossard** [comment]
@dotnfc, could you have a look at #789? I do have a question specifically about pinout.

**Comment by dotnfc** [comment]
> @dotnfc: could you rebase your changes on the `experimental_compilers` branch and do a pull request to that branch?

done with #805. please check for that

**Pull request closed without merging**
