### PR TITLE
Wait for buffer status on lpc11u35 EP read

### LINKED ISSUE #517: assert seen in usbd_LPC11Uxx.c for RZ_A1H
DETAILS.TXT

# DAPLink Firmware - see https://mbed.com/daplink
Unique ID: 5500000003e39cf200000000000000000000000097969902
HIC ID: 97969902
Auto Reset: 0
Automation allowed: 0
Overflow detection: 0
Daplink Mode: Interface
Interface Version: 0250
Git SHA: 6fece7592b9f0a57c032e48bfb70bd53d02dc33c
Local Mods: 0
USB Interfaces: MSD, CDC, HID, WebUSB
Interface CRC: 0x74181e66
Remount count: 5
URL: https://mbed.org/device/?code=5500000003e39cf200000000000000000000000097969902?version=0250?target_id=@T

Assert
File: ..\..\..\source\hic_hal\nxp\lpc11u35\usbd_LPC11Uxx.c
Line: 555
Source: Application

Steps to reproduce 
1)  have a machine with more then 10 devices 
2) try flashing all the devices at once. we will see above failure

above steps are not perfect will try to provide better procedure this happened in CI environment.

### PR DESCRIPTION
**Pull request by brianesquilona**
Closes #517

### CODE REVIEW

**Comment by flit** [comment]
How is this problem reproduced?

**Comment by brianesquilona** [comment]
I'm still waiting for my logs in the CI, but this is hard to reproduce, this issue is related #517.

**Comment by flit** [comment]
Ok. Remember to put a "Closes #517". in the description to link the PR to the issue.

**Pull request merged**
