### PR TITLE
LPC4322 Protect IAP function calls

### PR DESCRIPTION
**Pull request by mmahadevan108**
Fix for Issue 340

Signed-off-by: Mahesh Mahadevan <Mahesh.Mahadevan@nxp.com>

### CODE REVIEW

**Comment by mmahadevan108** [comment]
This is a fix for https://github.com/ARMmbed/DAPLink/issues/340

**Comment by c1728p9** [comment]
Thanks for the PR @mmahadevan108. I think the function ```read_unique_id``` also uses IAP calls and also needs to be protected. Do any of the IAP calls use global ram which needs to be reserved? This was needed for the lpc11u35 - https://github.com/ARMmbed/DAPLink/pull/255/files#diff-8d605fbb650e7188d924bb38e686e453R31.

**Comment by c1728p9** [comment]
@mmahadevan108 any updates on this?

**Comment by mmahadevan108** [comment]
@c1728p9 I have updated the patch to protect the IAP calls in read_unique_id function. We do not reserve any global ram for lpc4322 driver.

**Comment by c1728p9** [comment]
Hi @mmahadevan108, looking at the LPC4322 datasheet it looks like RAM does need to be reserved.

From sections 6.8 of UM10503:
**IAP commands which result in a flash write/erase operation use 32 bytes of space in the top portion of the on-chip RAM for execution. The user program should not be using this space if IAP flash programming is permitted in the application.**

**Comment by mmahadevan108** [comment]
The flash programming code uses RAM located at 0x10080000. This SRAM is not used by LPC4322 DAPLink code.

**Comment by c1728p9** [comment]
Ah good, I didn't realize this was in a separate RAM bank.

**Comment by mmahadevan108** [comment]
Can this be merged in?

**Pull request merged**
